# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches:
      - master

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          usedocker: true
          docker_build_args: |
            MY_SECRET
          
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_heroku_process_type: web
        env:
          HD_MY_SECRET: ${{ secrets.TEST }}
        
### ⬆ IMPORTANT PART ⬆ ###

