name: test if a secrets if ok

on:
  push: {}

jobs:
  checksecret:
    name: check if MY_SECRET is set in github secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check whether unity activation requests should be done
        env:
            MY_SECRET: ${{ secrets.TEST }}
        run: echo $MY_SECRET
